Repository semaphore-protocol/taz-apps, pull requests merged in 2022-10, with the labels that each got.

#36 API endpoint for active canvases
  apps/web-app/pages/api/getActiveCanvases.js
Labels: feature :rocket:

#37 Arboard, Drawing modal and Processing modal UX updates
  apps/web-app/components/ArtBoard/View.js
  apps/web-app/components/ArtBoard/drawingModal.js
  apps/web-app/components/ArtBoard/generateTile.js
  apps/web-app/components/ArtBoard/index.js
  apps/web-app/components/svgElements/Flame.js
  apps/web-app/components/svgElements/TrashCan.js
  apps/web-app/components/svgElements/Undo.js
  apps/web-app/pages/answers/[parentMessageId].js
  apps/web-app/pages/api/mintFullCanvas.js
  apps/web-app/pages/questions/index.js
  apps/web-app/public/sw.js.map
Labels: design :art:

#25 feat: create booth display page
  apps/web-app/components/TazBooth/BoothArtboardCard/index.tsx
  apps/web-app/components/TazBooth/BoothContent/index.tsx
  apps/web-app/components/TazBooth/BoothFooter/index.tsx
  apps/web-app/components/TazBooth/BoothLogo/index.jsx
  apps/web-app/components/svgElements/ArtBunnyBooth.jsx
  apps/web-app/pages/api/getActiveCanvases.js
  apps/web-app/pages/booth-display/index.tsx
  apps/web-app/pages/booth-display/mock-data.ts
  apps/web-app/public/sw.js.map
  apps/web-app/tailwind.config.js
  yarn.lock
Labels: feature :rocket:

#69 Docs/readme files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  apps/contracts/README.md
  apps/web-app/README.md
Labels: documentation :book:
